language: c
sudo: required
branches:
  only:
    - "master"
    - "develop"

before_install:
  - sudo add-apt-repository -y ppa:voltvisionfrenchy/ola
  - sudo apt-get update
  - sudo apt-get install -y libola-dev


before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make && make olaclient && ctest -V
